backend:
  name: github
  repo: TU_USUARIO/TU_REPOSITORIO
  branch: main

media_folder: "imagenes"
public_folder: "/imagenes"

collections:
  - name: inicio
    label: Inicio
    files:
      - label: Página de inicio
        name: inicio
        file: datos/inicio.json
        fields:
          - {label: Título, name: title, widget: string}
          - {label: Subtítulo, name: subtitle, widget: string}
          - {label: Texto, name: text, widget: text}
          - {label: Imagen, name: image, widget: image, required: false}

  - name: agenda
    label: Agenda
    files:
      - label: Eventos
        name: agenda
        file: datos/agenda.json
        fields:
          - label: Eventos
            name: items
            widget: list
            fields:
              - {label: ID, name: id, widget: number}
              - {label: Título, name: title, widget: string}
              - {label: Fecha inicio, name: start, widget: datetime}
              - {label: Fecha fin, name: end, widget: datetime, required: false}
              - {label: Imagen, name: image, widget: image, required: false}
              - {label: Texto, name: text, widget: text}

  - name: acampadas
    label: Acampadas
    files:
      - label: Acampadas
        name: acampadas
        file: datos/acampadas.json
        fields:
          - label: Acampadas
            name: items
            widget: list
            fields:
              - {label: ID, name: id, widget: number}
              - {label: Título, name: title, widget: string}
              - {label: Fecha, name: date, widget: date}
              - {label: Portada, name: cover, widget: image, required: false}
              - {label: Texto, name: text, widget: text}
              - label: Galería
                name: images
                widget: list
                field: {label: Imagen, name: image, widget: image}

  - name: scouters
    label: Scouters
    files:
      - label: Scouters
        name: scouters
        file: datos/scouters.json
        fields:
          - label: Scouters
            name: items
            widget: list
            fields:
              - {label: ID, name: id, widget: number}
              - {label: Nombre, name: name, widget: string}
              - {label: Cargo, name: role, widget: string}
              - {label: Imagen, name: image, widget: image, required: false}
              - {label: Texto, name: text, widget: text}

  - name: faq
    label: Preguntas frecuentes
    files:
      - label: FAQ
        name: faq
        file: datos/faq.json
        fields:
          - label: Preguntas
            name: items
            widget: list
            fields:
              - {label: ID, name: id, widget: number}
              - {label: Pregunta, name: q, widget: string}
              - {label: Respuesta, name: a, widget: text}
